# Generated by Django 5.2.5 on 2025-08-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area_sq_km",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegionInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "top_schemes",
                    models.JSONField(
                        help_text="Top schemes in this region with their metrics"
                    ),
                ),
                (
                    "sentiment_avg",
                    models.FloatField(help_text="Average sentiment score (-1 to 1)"),
                ),
                (
                    "complaints_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of complaints in this region"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region Insight",
                "verbose_name_plural": "Region Insights",
                "ordering": ["-created_at"],
            },
        ),
    ]
